const RESET_STATE = 'RESET_STATE';
const SET_DATA_SHOPPING_CAR = 'SET_DATA_SHOPPING_CAR';
const SET_DATA_FILTER = 'SET_DATA_FILTER';
const SET_DATA_FILTER_PAGINATION = 'SET_DATA_FILTER_PAGINATION';

export {
    RESET_STATE,
    SET_DATA_FILTER,
    SET_DATA_FILTER_PAGINATION,
    SET_DATA_SHOPPING_CAR,
};
